
-- создать таблицу users
-- drop ALL OBJECTS;
drop table if exists users, items, bookings;

CREATE TABLE IF NOT EXISTS users (
 --id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name varchar (255) NOT NULL,
    email varchar(512) NOT NULL unique
 --   CONSTRAINT pk_user PRIMARY KEY (id)
-- CONSTRAINT UQ_USER_EMAIL unique (email)
-- unique (email)
-- first_name varchar(100),
--  last_name varchar(100),
--   registration_date timestamp,
--   state varchar(50)
    );

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    is_available bool, -- NOT NULL
    owner_id BIGINT NOT NULL references users (id) on delete cascade
  --  request_id BIGINT NOT NULL
--    CONSTRAINT fk_user_id FOREIGN KEY(user_id)
--    REFERENCES users(id) ON delete CASCADE

    );

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    start_date timestamp,
    end_date timestamp,
    item_id BIGINT NOT NULL references items (id) on delete cascade,
    booker_id BIGINT NOT NULL references users (id) on delete cascade,
    status varchar (100)


);